export const GET_PRODUCTS = 'http://localhost:5000/api/v1/products/'
export const GET_PRODUCT = 'http://localhost:5000/api/v1/products/'
export const DELETE_PRODUCT = 'http://localhost:5000/api/v1/products/'
export const CREATE_PRODUCT = 'http://localhost:5000/api/v1/products/'
export const MAKE_PRODUCT_REVIEW = 'http://localhost:5000/api/v1/products/'